### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by xtyuns** [ja-netfilter/ja-netfilter-sample-plugin#2]
Hi neo peng, I',m a new to java so I cannnot understand what's the meaning of the following code, and how to tigger it, can u help me?

https://github.com/pengzhile/ja-netfilter-sample-plugin/blob/50c69a658ccafd77ae9d14e4754507d6919d7872/src/main/java/my/sample/plugin/TestTransformer.java#L9

**Comment by CocosGames** [comment]
类调用钩子。netfilter触发点。
