### ISSUE TITLE
没有增强 ，原因不明

### ISSUE THREAD

**Issue by ivanmissu** [ja-netfilter/ja-netfilter-sample-plugin#4]
替换了sql的一个jar，打印执行sql，使用arthas是可以看到的
启动没有报错，输出了A javaagent framework :)   ，使用arthas查看AbstractPreparedQuery 没有被增强
`package my.sample.plugin;

import com.janetfilter.core.commons.DebugInfo;
import com.janetfilter.core.plugin.MyTransformer;
import javassist.ClassPool;
import javassist.CtClass;
import javassist.CtMethod;

public class TestTransformer implements MyTransformer {
    @Override
    public String getHookClassName() {
        return "com/mysql/cj/AbstractPreparedQuery";
    }

    @Override
    public byte[] transform(String className, byte[] classBytes, int order) throws Exception {
        DebugInfo.output("................");
        System.out.println("--------------------------------------");
        System.out.println("Oh! It's you: " + className);
        System.out.flush();
        ClassPool cpool = ClassPool.getDefault();
        CtClass ctClass = cpool.get("com.mysql.cj.AbstractPreparedQuery");
        CtMethod ctMethod = ctClass.getDeclaredMethod("getOriginalSql");
        ctMethod.setBody("{ " +
                "\n" +
                "System.out.println(this.originalSql);" +
                "\n" +
                "return this.originalSql; " +
                "\n" +
                "}");
        return ctClass.toBytecode();
    }
}
`

**Comment by pengzhile** [comment]
启动命令加-Djanf.debug=1，看输出里你插件加载没

**Comment by ivanmissu** [comment]
> 

加了   插件内的日志没输出

**Comment by pengzhile** [comment]
> 加了 插件内的日志没输出 框架日志输出了

框架日志里有加载你插件的输出吗？是不是你插件没加载到？

**Comment by ivanmissu** [comment]
> 

com.janetfilter.core.Initializer.init(Initializer.java:11) DEBUG : Environment: {
	baseDir=/Users/apc/develops/workspaces/githubWorkspaces/ja-netfilter-sample-plugin/target, 
	agentFile=/Users/apc/develops/workspaces/githubWorkspaces/ja-netfilter-sample-plugin/target/sample-plugin-jar-with-dependencies.jar, 
	configDir=/Users/apc/develops/workspaces/githubWorkspaces/ja-netfilter-sample-plugin/target/config, 
	pluginsDir=/Users/apc/develops/workspaces/githubWorkspaces/ja-netfilter-sample-plugin/target/plugins, 
	nativePrefix=W8cqYYzLSAIkRNl_
框架日志输出了这个

**Comment by ivanmissu** [comment]
pom插件我改成这个了

<manifestEntries>
    <JANF-Plugin-Entry>my.sample.plugin.MyPluginEntry</JANF-Plugin-Entry>
    <Premain-Class>com.janetfilter.core.Launcher</Premain-Class>
    <Main-Class>com.janetfilter.core.Launcher</Main-Class>
    <Can-Redefine-Classes>true</Can-Redefine-Classes>
    <Can-Retransform-Classes>true</Can-Retransform-Classes>
    <Can-Set-Native-Method-Prefix>true</Can-Set-Native-Method-Prefix>
</manifestEntries>

**Comment by pengzhile** [comment]
为什么你的agentFile不是ja-netfilter.jar?

**Comment by pengzhile** [comment]
> pom插件我改成这个了
> `<manifestEntries> <JANF-Plugin-Entry>my.sample.plugin.MyPluginEntry</JANF-Plugin-Entry> <Premain-Class>com.janetfilter.core.Launcher</Premain-Class> <Main-Class>com.janetfilter.core.Launcher</Main-Class> <Can-Redefine-Classes>true</Can-Redefine-Classes> <Can-Retransform-Classes>true</Can-Retransform-Classes> <Can-Set-Native-Method-Prefix>true</Can-Set-Native-Method-Prefix> </manifestEntries>`

你一个插件改成这样干啥？

**Comment by ivanmissu** [comment]
> 

不改动的话  启动不了  找不到Premain

**Comment by pengzhile** [comment]
> 不改动的话 启动不了 找不到Premain

你的插件编译完了，丢进ja-netfilter.jar所在目录的plugins目录中

**Comment by ivanmissu** [comment]
> > 不改动的话 启动不了 找不到Premain
> 
> 你的插件编译完了，丢进ja-netfilter.jar所在目录的plugins目录中

额  我理解错了  我以为把ja-netfilter.jar当成开发框架  然后直接使用插件包了  我再试试
